#!/bin/bash
set -e

jshint ./immunity_users/static/immunity-users/js/*.js

echo ''
echo 'Compiling translations'
cd immunity_users
django-admin compilemessages
cd ..

immunity-qa-check \
      --migrations-to-ignore 2 \
      --migration-path './immunity_users/migrations' \
      --migration-module immunity_users

echo ''
echo 'Running checks for testapp'

immunity-qa-check \
      --skip-isort \
      --skip-flake8 \
      --skip-black \
      --skip-checkmigrations \
      --skip-checkendline \
      --skip-checkcommit \
      --migration-path './tests/testapp/migrations' \
      --migration-module testapp

echo ''
echo 'Running checks for SAMPLE_APP'

SAMPLE_APP=1 immunity-qa-check \
      --skip-isort \
      --skip-flake8 \
      --skip-black \
      --skip-checkmigrations \
      --skip-checkendline \
      --skip-checkcommit \
      --migration-path './tests/immunity2/sample_ipam/migrations' \
      --migration-module sample_users
